#!/usr/bin/env python
import sys, os


def options(opt):
    opt.load('compiler_cxx')
    opt.load('boost')
    opt.load('gtest')


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('boost')
    cfg.load('gtest')

    cfg.check_boost(
            lib='serialization system thread',
            uselib_store='BOOST4ZTL')

def build(bld):

    bld(
        target          = 'ztl_tests',
        features        = 'cxx cxxprogram gtest',
        source          = bld.path.ant_glob('*.cc'),
        use             = ['ZTL', 'BOOST4ZTL', 'gtest'],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O1',
                '-std=c++0x',
                '-Wall',
                '-Wextra',
                '-pedantic',
                #'-D_GLIBCXX_PROFILE',
                #'-D_GLIBCXX_DEBUG'
            ],
        includes       = '.',
    )
